# -----------------------
# RuneCore Configuration
# -----------------------


# 一般設定
plugin:
  ## /patchnote で表示されるパッチノートの URL
  patchNoteURL: "https://example.com"
  ## サーバー参加時に送信される Motd
  motd:
    - " --- Welcome to Rune of Mer! --- "
    - "公式サイト: https://example.com"
  ## 初見プレイヤー対応に関する設定
  noKnownPlayers:
    ### 初見プレイヤーが参加時に送信される Motd
    firstMotd:
      - "Rune of Mer へようこそ!"
      - "まずはチュートリアルを受けましょう!"
    ### 初見プレイヤーに最初に支給される所持金
    tutorialRune: 1000
    ### チュートリアルを受けた際に入手できる経験値 (チュートリアルを受けた際の報酬として)
    tutorialExp: 1000

# データベース設定
database:
  ## データベースのホスト
  host: "mariadb"
  ## データベースのポート
  port: 3306
  ## データベース名
  name: "runecore_db"
  ## データベースに接続する場合のユーザー名．`root` での接続はしないでください．
  username: "runecore"
  ## データベースに接続する場合のパスワード
  password: "runecore"
  ## HikariCP でのプール設定 (詳細はこちら: https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#gear-configuration-knobs-baby)
  ## 小規模構成で RuneCore を使う場合は `maximumSize` を `5`, `minimumIdle` を `1` で運用することが推奨されます．
  ## 以下の設定は本来であれば変更不要です．
  pool:
    ### プールで使用できる最大接続数
    maximumSize: 10
    ### プールで維持する最小限のアイドル接続数．
    ### この値が `maximumPoolSize` よりも小さい場合は `idleTimeout` を超えてアイドル状態にある接続は削除されます．
    minimumIdle: 2
    ### 接続がプール内でアイドル状態のまま維持できる最大時間 (ミリ秒単位)
    ### 例えばデフォルト値では1分間アイドル状態の接続が対象となります．`minimumIdle` の値を超えている場合のみ，この時間をすぎたアイドル接続は削除されます．
    idleTimeout: 60000
    ### プールから接続を取得するために待機する最大時間 (ミリ秒単位)
    ### 設定した制限時間を超えても接続を取得できない場合はエラーとなります．
    connectionTimeout: 30000

# テレポート設定
teleport:
  ## テレポートリクエストのタイムアウト時間 (秒)
  requestTimeoutSeconds: 60
  ## デフォルトのワープスロット数
  defaultWarpSlots: 3
  ## テレポート料金設定
  costs:
    ### 最大料金 (Rune)
    maxCost: 1000
    ### ワールド間移動の基本料金 (Rune)
    crossWorldBaseCost: 50

  # ワールド設定
  # name - ワールドの名前 (RuneCore はワールドの判定を名前ベース行うため，正しく指定してください)
  # crossWorldCost - ワールド間移動の追加料金 (teleport.costs.crossWorldBaseCost の計算で使用されます)
  world:
    ## 生活ワールド - プレイヤーが生活するワールド
    life:
      name: "world_life"
      crossWorldCost: 20
    ## 資源ワールド - プレイヤーが資源を確保するワールド
    resource:
      name: "world_resource"
      crossWorldCost: 50
    ## 資源ネザーワールド - プレイヤーが資源を確保するネザーワールド
    resourceNether:
      name: "world_resource_nether"
      crossWorldCost: 55
    ## 資源エンドワールド - プレイヤーが資源を確保するネザーワールド
    resourceEnd:
      name: "world_resource_end"
      crossWorldCost: 55
    ## ダークゾーン - PvP On / アイテムロストありのバトル型コンテンツのワールド  - v0.1.0 時点ではこのコンテンツはまだ未実装なので，使用されない
    dz:
      name: "world_dz"
      crossWorldCost: 500
      ### DZ を解放しない場合は false にする
      enabled: false
      ### 同時可能接続人数
      ### DZ はバトル型コンテンツのため，大人数で入ることは想定していません．ここで指定した人数ワールドにいる場合接続しようとするとエラーになります
      maxMemberSize: 10
    ## PvPワールド - PvP On / アイテムロストなしの気軽なバトル型コンテンツのワールド
    pvp:
      name: "world_pvp"
      ### PvP は別にお金を取ることはしない
      crossWorldCost: 0

