services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: runecore-debug-server
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - minecraft-data:/data
      - ../build/libs:/plugins:ro
      - ./plugins:/data/plugins
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.3"
      MEMORY: "1G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
      DIFFICULTY: "peaceful"
      MAX_PLAYERS: "3"
      ONLINE_MODE: "false"
      VIEW_DISTANCE: "5"
      SERVER_NAME:  "Rune Core Debug Server"
      MOTD: "ยง6Rune Core Debug Server"
      SYNC_SKIP_NEWER_IN_DESTINATION:  "false"
    depends_on:
      mariadb:
        condition: service_healthy
    tty: true
    stdin_open: true

  mariadb:
    image: mariadb:12.1.2
    container_name: runecore-mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE:  "runecore_db"
      MYSQL_USER: "runecore"
      MYSQL_PASSWORD: "runecore"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  minecraft-data:
  mariadb-data:
